export const SET_TOKEN_LIST = "SET_TOKEN_LIST";
export const SET_NONCE_SYNC = "SET_NONCE_SYNC";
export const SET_BLOCKNUMBER_SYNC = "SET_BLOCKNUMBER_SYNC";
export const SET_WALLET_TYPE = "SET_WALLET_TYPE";
export const SET_MAKER_VAULT_COUNT = "SET_MAKER_VAULT_COUNT";
export const SET_TRANSACTION_WATCH = "SET_TRANSACTION_WATCH";
export const UPDATE_TRANSACTION_WATCH = "UPDATE_TRANSACTION_WATCH";
export const RESET_TRANSACTION_WATCH = "RESET_TRANSACTION_WATCH";
